### ISSUE TITLE
Autorest generated client returns object and is unclear from a consumer point of view

### ISSUE THREAD

**Issue by base2browns** [kmdlogic/kmd-logic-sms-client#14]
Spoke to @adamchester about this.
autorest returns object when there are multiple return types, e.g. 200, 201, 401, 403. As a consumer I have no guidance how to decode this method. The only way I can find out is F5.

**Comment by adamchester** [comment]
Thanks @base2browns, we are going to investigate this a little :+1:

**Comment by adamchester** [comment]
I've done a little research on this (not enough, but a quick survey).

The only reasonable solutions I can see are:

1. Status codes `2xx` results in a single schema, and `4xx` and `5xx` status codes result in exceptions, which may have structured things attached to them. Probably a custom written client would be necessary at this stage, unless I can find a generator that does it reliably from an Open API spec.
2. A custom-written C# client which uses a custom result type that includes all the various result types with a discriminator (aka discriminated union). Since C# doesn't really support this, I'm not entirely sure how it would work, but it could definitely be done.

Still need to search a bit further to see if any generators like autorest or nswag can do this, but my searching so far has come up empty.

**Comment by adamchester** [comment]
Unfortunately we haven't found any sensible path forward with this one yet, so I'm closing it for now.

If anyone has any further information about tooling or patterns or whatever that could help progress this one forward, please jump in here and we can reopen it!
